### ISSUE TITLE
Can't build packages

### ISSUE THREAD

**Issue by mthmulders** [facette/buildenv#1]
After a fresh clone, I issued `make images`. The container images are being built correctly:

    docker images | grep facette
    facette/buildenv                        stretch-armel       1b576e49cbe6        21 minutes ago      1.01GB
    facette/buildenv                        stretch-arm64       e09a26fe52d8        22 minutes ago      1.01GB
    facette/buildenv                        stretch-amd64       980c4f5388c1        23 minutes ago      825MB
    facette/buildenv                        bionic-amd64        a7b7e68edeaa        27 minutes ago      766MB

Then I issued `make release`. This fails:

    make release
    docker run --rm -ti -v /path/to/facette/buildenv/dist:/tmp/build facette/buildenv:stretch-amd64 bash -c "mkdist binary master"
    bash: mkdist: command not found
    make: [binary-stretch-amd64] Error 127 (ignored)
    docker run --rm -ti -v /path/to/facette/buildenv/dist:/tmp/build facette/buildenv:stretch-arm64 bash -c "mkdist binary master"
    bash: mkdist: command not found
    make: [binary-stretch-arm64] Error 127 (ignored)
    docker run --rm -ti -v /path/to/facette/buildenv/dist:/tmp/build facette/buildenv:stretch-armel bash -c "mkdist binary master"
    bash: mkdist: command not found
    make: [binary-stretch-armel] Error 127 (ignored)
    docker run --rm -ti -v /path/to/facette/buildenv/dist:/tmp/build facette/buildenv:bionic-amd64 bash -c "mkdist debian master"
    bash: mkdist: command not found
    make: [debian-bionic-amd64] Error 127 (ignored)
    docker run --rm -ti -v /path/to/facette/buildenv/dist:/tmp/build facette/buildenv:stretch-amd64 bash -c "mkdist debian master"
    bash: mkdist: command not found
    make: [debian-stretch-amd64] Error 127 (ignored)
    docker run --rm -ti -v /path/to/facette/buildenv/dist:/tmp/build facette/buildenv:stretch-arm64 bash -c "mkdist debian master"
    bash: mkdist: command not found
    make: [debian-stretch-arm64] Error 127 (ignored)
    docker run --rm -ti -v /path/to/facette/buildenv/dist:/tmp/build facette/buildenv:stretch-armel bash -c "mkdist debian master"
    bash: mkdist: command not found
    make: [debian-stretch-armel] Error 127 (ignored)

I can't figure out where `mkdist` should come from. Am I missing something in the instructions?

**Comment by mthmulders** [comment]
@vbatoufflet Any idea? Am I missing something here?

**Comment by vbatoufflet** [comment]
Hi @mthmulders,

Sorry for the delay.

Indeed this repository wasn't completely up-to-date. Once the images retrieved from the Docker Hub or built here, you'll have to execute `./misc/scripts/release.sh` from Facette source directory.

Let me know if something is still missing.

**Comment by vbatoufflet** [comment]
If you don't want to build for all the distributions (while located in Facette source directory), you can target `stretch-amd64` like this:

    docker run --rm -v $PWD:/root/go/src/facette.io/facette facette/buildenv:stretch-arm64 make dist-deb

The files will be available in the `dist/` directory upon success.

**Comment by mthmulders** [comment]
Thanks, that solves it. I am now able to build packages myself, too. This means I can try to build armhf packages 👍
